site_name: "Práctica S3 con CRR Y MRAP"
theme:
  name: material
  locale: "es"
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Cambiar a modo oscuro
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Cambiar a modo light
nav:
    - Enunciado: "index.md"
    - Práctica: "UD2-CRR-practica.md"
    - Formato entrega: "Entrega.md"
